<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ebrahim Alhaddad">
<meta name="dcterms.date" content="2025-03-15">

<title>Uplift modeling for an ads campaign – Ebrahim’s Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-610593e65a40a0629ca575dfc540a55b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Ebrahim’s Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#uplift-modeling-analysis" id="toc-uplift-modeling-analysis" class="nav-link active" data-scroll-target="#uplift-modeling-analysis"><span class="header-section-number">1</span> Uplift Modeling Analysis</a>
  <ul class="collapse">
  <li><a href="#loading-the-data" id="toc-loading-the-data" class="nav-link" data-scroll-target="#loading-the-data"><span class="header-section-number">1.1</span> Loading the Data</a></li>
  <li><a href="#preparing-the-data-for-uplift-modeling" id="toc-preparing-the-data-for-uplift-modeling" class="nav-link" data-scroll-target="#preparing-the-data-for-uplift-modeling"><span class="header-section-number">1.2</span> Preparing the Data for Uplift Modeling</a></li>
  <li><a href="#we-will-create-our-training-and-validation-sets-stratified-over-treatment-and-response-to-ensure-balance" id="toc-we-will-create-our-training-and-validation-sets-stratified-over-treatment-and-response-to-ensure-balance" class="nav-link" data-scroll-target="#we-will-create-our-training-and-validation-sets-stratified-over-treatment-and-response-to-ensure-balance"><span class="header-section-number">1.3</span> We will create our training and validation sets stratified over treatment and response to ensure balance</a></li>
  <li><a href="#building-uplift-models" id="toc-building-uplift-models" class="nav-link" data-scroll-target="#building-uplift-models"><span class="header-section-number">1.4</span> Building Uplift Models</a></li>
  <li><a href="#evaluating-model-performance-and-visualizing-results" id="toc-evaluating-model-performance-and-visualizing-results" class="nav-link" data-scroll-target="#evaluating-model-performance-and-visualizing-results"><span class="header-section-number">1.5</span> Evaluating Model Performance and Visualizing Results</a></li>
  <li><a href="#nonlinear-models-mlp" id="toc-nonlinear-models-mlp" class="nav-link" data-scroll-target="#nonlinear-models-mlp"><span class="header-section-number">1.6</span> Nonlinear models (MLP)</a></li>
  <li><a href="#nonlinear-models-xgboost" id="toc-nonlinear-models-xgboost" class="nav-link" data-scroll-target="#nonlinear-models-xgboost"><span class="header-section-number">1.7</span> Nonlinear models (xgboost)</a></li>
  <li><a href="#key-results" id="toc-key-results" class="nav-link" data-scroll-target="#key-results"><span class="header-section-number">1.8</span> Key Results</a>
  <ul class="collapse">
  <li><a href="#baseline-uplift-model" id="toc-baseline-uplift-model" class="nav-link" data-scroll-target="#baseline-uplift-model"><span class="header-section-number">1.8.1</span> Baseline Uplift Model</a></li>
  <li><a href="#mlp-uplift-model" id="toc-mlp-uplift-model" class="nav-link" data-scroll-target="#mlp-uplift-model"><span class="header-section-number">1.8.2</span> MLP Uplift Model</a></li>
  <li><a href="#xgboost-uplift-model" id="toc-xgboost-uplift-model" class="nav-link" data-scroll-target="#xgboost-uplift-model"><span class="header-section-number">1.8.3</span> XGBoost Uplift Model</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">1.9</span> Conclusion</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="../../_notebook/uplift_summ-preview.html"><i class="bi bi-journal-code"></i>Uplift Modeling Analysis</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Uplift modeling for an ads campaign</h1>
<p class="subtitle lead">Exploring the difference between propensity and uplift modeling using treatment effects in an ads campaign</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ebrahim Alhaddad </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 15, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="uplift-modeling-analysis" class="level1 quarto-embed-nb-cell" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Uplift Modeling Analysis</h1>
<p>This notebook explores uplift modeling, a data science technique used to measure the incremental impact of a treatment or intervention on customer behavior. For example, in marketing, uplift modeling helps determine how much an advertisement increases the chance of a customer making a purchase compared to not seeing the ad.</p>
<p>We’ll work with customer data from two groups: - <strong>Control group</strong>: Customers who did not receive the treatment (e.g., no ad). - <strong>Treatment group</strong>: Customers who received the treatment (e.g., saw an ad).</p>
<p>The goal is to build models that predict the uplift—the difference in response rates between treated and untreated customers—and identify which customers are most likely to respond positively to the treatment.</p>
<p>There’s a clear distinction between using a propensity model and an uplift model. Propensity model do not account for treatment effects and predict overall response rate. Meanwhile, uplift models predict response rate <strong>caused by</strong> treatment. Compared to a propensity model, an uplift model can help us distinguish between four segments of customers:</p>
<table>
<thead>
<tr>
<th>
</th>
<th>
Untreated Low
</th>
<th>
Untreated High
</th>
</tr>
</thead>
<tbody>
<tr>
<th>
Treated Low
</th>
<td>
Lost Cause
</td>
<td>
Ignore
</td>
</tr>
<tr>
<th>
Treated High
</th>
<td>
Target
</td>
<td>
Sure Thing
</td>
</tr>
</tbody>
</table>
<p>This allows us to direct marketing investments more strategically and compute more accurate ROME. More precisely, the Lost Cause and Ignore segments should not be targeted as that will yield a negligible or negative return. While the Sure Thing segment returns should not be attributed to marketing spend.</p>
<p>We’ll use Python libraries like Polars for data manipulation and pyrsm for statistical analysis and modeling.</p>
<section id="loading-the-data" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="loading-the-data"><span class="header-section-number">1.1</span> Loading the Data</h2>
<p>To perform uplift analysis, we need data from both the control and treatment groups. These datasets contain customer information and their responses.</p>
<ul>
<li>The control group data represents customers who were not exposed to the treatment.</li>
<li>The treatment group data represents customers who were exposed to the treatment.</li>
</ul>
<p>We’ll load these datasets using Polars, a fast data processing library, and examine their structure.</p>
<div id="cell-2" class="cell" data-execution_count="38">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">## loading the organic data - this dataset must NOT be changed</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>cg_organic_control <span class="op">=</span> pl.read_parquet(<span class="st">"data/cg_organic_control.parquet"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>cg_organic_control.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (5, 20)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">converted</th>
<th data-quarto-table-cell-role="th">GameLevel</th>
<th data-quarto-table-cell-role="th">NumGameDays</th>
<th data-quarto-table-cell-role="th">NumGameDays4Plus</th>
<th data-quarto-table-cell-role="th">NumInGameMessagesSent</th>
<th data-quarto-table-cell-role="th">NumSpaceHeroBadges</th>
<th data-quarto-table-cell-role="th">NumFriendRequestIgnored</th>
<th data-quarto-table-cell-role="th">NumFriends</th>
<th data-quarto-table-cell-role="th">AcquiredSpaceship</th>
<th data-quarto-table-cell-role="th">AcquiredIonWeapon</th>
<th data-quarto-table-cell-role="th">TimesLostSpaceship</th>
<th data-quarto-table-cell-role="th">TimesKilled</th>
<th data-quarto-table-cell-role="th">TimesCaptain</th>
<th data-quarto-table-cell-role="th">TimesNavigator</th>
<th data-quarto-table-cell-role="th">PurchasedCoinPackSmall</th>
<th data-quarto-table-cell-role="th">PurchasedCoinPackLarge</th>
<th data-quarto-table-cell-role="th">NumAdsClicked</th>
<th data-quarto-table-cell-role="th">DaysUser</th>
<th data-quarto-table-cell-role="th">UserConsole</th>
<th data-quarto-table-cell-role="th">UserHasOldOS</th>
</tr>
<tr class="even">
<td>cat</td>
<td>i32</td>
<td>i32</td>
<td>i32</td>
<td>i32</td>
<td>i32</td>
<td>i32</td>
<td>i32</td>
<td>cat</td>
<td>cat</td>
<td>i32</td>
<td>i32</td>
<td>i32</td>
<td>i32</td>
<td>cat</td>
<td>cat</td>
<td>i32</td>
<td>i32</td>
<td>cat</td>
<td>cat</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"no"</td>
<td>7</td>
<td>18</td>
<td>0</td>
<td>124</td>
<td>0</td>
<td>81</td>
<td>0</td>
<td>"yes"</td>
<td>"no"</td>
<td>8</td>
<td>0</td>
<td>0</td>
<td>4</td>
<td>"no"</td>
<td>"yes"</td>
<td>3</td>
<td>2101</td>
<td>"no"</td>
<td>"no"</td>
</tr>
<tr class="even">
<td>"no"</td>
<td>10</td>
<td>3</td>
<td>2</td>
<td>60</td>
<td>0</td>
<td>18</td>
<td>479</td>
<td>"no"</td>
<td>"no"</td>
<td>10</td>
<td>7</td>
<td>0</td>
<td>0</td>
<td>"yes"</td>
<td>"no"</td>
<td>7</td>
<td>1644</td>
<td>"yes"</td>
<td>"no"</td>
</tr>
<tr class="odd">
<td>"no"</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>"no"</td>
<td>"no"</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>2</td>
<td>"no"</td>
<td>"no"</td>
<td>8</td>
<td>3197</td>
<td>"yes"</td>
<td>"yes"</td>
</tr>
<tr class="even">
<td>"no"</td>
<td>2</td>
<td>11</td>
<td>1</td>
<td>125</td>
<td>0</td>
<td>73</td>
<td>217</td>
<td>"no"</td>
<td>"no"</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>"yes"</td>
<td>"no"</td>
<td>6</td>
<td>913</td>
<td>"no"</td>
<td>"no"</td>
</tr>
<tr class="odd">
<td>"no"</td>
<td>8</td>
<td>15</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>6</td>
<td>51</td>
<td>"yes"</td>
<td>"no"</td>
<td>0</td>
<td>0</td>
<td>2</td>
<td>1</td>
<td>"yes"</td>
<td>"no"</td>
<td>21</td>
<td>2009</td>
<td>"yes"</td>
<td>"no"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="preparing-the-data-for-uplift-modeling" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="preparing-the-data-for-uplift-modeling"><span class="header-section-number">1.2</span> Preparing the Data for Uplift Modeling</h2>
<p>To build an uplift model, we need to combine the control and treatment data into one dataset. We’ll add a binary variable called ‘ad’ (1 for treated, 0 for control) to indicate which group each customer belongs to. This setup allows machine learning models to learn the difference in responses between the groups.</p>
<p>First, we load an additional dataset and prepare the combined data.</p>
<div id="cell-4" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>cg_ad_random <span class="op">=</span> cg_ad_random.with_columns(pl.lit(<span class="dv">1</span>).alias(<span class="st">"ad"</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>cg_organic_control <span class="op">=</span> cg_organic_control.with_columns(pl.lit(<span class="dv">0</span>).alias(<span class="st">"ad"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a variable called 'cv1_yes' that has value 1 when conversion == 'yes', has value 0 when conversion == 'no'</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>cg_rct_stacked <span class="op">=</span> cg_rct_stacked.with_columns(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    pl.when(pl.col(<span class="st">"converted"</span>) <span class="op">==</span> <span class="st">"yes"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    .then(<span class="dv">1</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    .when(pl.col(<span class="st">"converted"</span>) <span class="op">==</span> <span class="st">"no"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    .then(<span class="dv">0</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    .otherwise(<span class="va">None</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    .alias(<span class="st">"cv1_yes"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>cg_rct_stacked[<span class="st">"cv1_yes"</span>].value_counts(sort<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">cv1_yes</th>
<th data-quarto-table-cell-role="th">count</th>
</tr>
<tr class="even">
<td>i32</td>
<td>u32</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>5619</td>
</tr>
<tr class="even">
<td>0</td>
<td>54381</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="we-will-create-our-training-and-validation-sets-stratified-over-treatment-and-response-to-ensure-balance" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="we-will-create-our-training-and-validation-sets-stratified-over-treatment-and-response-to-ensure-balance"><span class="header-section-number">1.3</span> We will create our training and validation sets stratified over treatment and response to ensure balance</h2>
<div id="cell-6" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>cg_rct_stacked <span class="op">=</span> cg_rct_stacked.with_columns(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    pl.Series(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"training"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>        rsm.model.make_train(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>            data<span class="op">=</span>cg_rct_stacked,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>            test_size<span class="op">=</span><span class="fl">0.3</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>            strat_var<span class="op">=</span>[<span class="st">"converted"</span>, <span class="st">"ad"</span>],</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>            random_state<span class="op">=</span><span class="dv">1234</span>,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>        ),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>cg_rct_stacked.group_by(<span class="st">"training"</span>).<span class="bu">len</span>().with_columns(</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    (pl.col(<span class="st">"len"</span>) <span class="op">/</span> pl.col(<span class="st">"len"</span>).<span class="bu">sum</span>()).<span class="bu">round</span>(<span class="dv">2</span>).alias(<span class="st">"proportion"</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="49">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">training</th>
<th data-quarto-table-cell-role="th">len</th>
<th data-quarto-table-cell-role="th">proportion</th>
</tr>
<tr class="even">
<td>i64</td>
<td>u32</td>
<td>f64</td>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>18000</td>
<td>0.3</td>
</tr>
<tr class="even">
<td>1</td>
<td>42000</td>
<td>0.7</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="building-uplift-models" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="building-uplift-models"><span class="header-section-number">1.4</span> Building Uplift Models</h2>
<p>With the combined dataset ready, we can now train machine learning models to predict uplift. Uplift is the difference in the probability of a positive outcome (e.g., purchase) between treated and untreated customers.</p>
<p>We’ll use various modeling techniques, including logistic regression and more advanced methods, to estimate the treatment effect. The models will help identify customers who are most likely to respond to the treatment.</p>
<p>In this step, we will skip some portions of the code used to train models to stay focused on uplift concepts</p>
<div id="cell-8" class="cell" data-execution_count="65">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>tab, tab_propen, df_master <span class="op">=</span> analyze_uplift(clf_control, clf_treatment, clf_propensity)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/..-..-_notebook-uplift_summ-cell-5-output-1.png" width="640" height="480" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/..-..-_notebook-uplift_summ-cell-5-output-2.png" width="640" height="480" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Expected incremental profit (uplift): 45907.75976154994
Expected incremental profit (propensity): -694.4477804681228</code></pre>
</div>
</div>
</section>
<section id="evaluating-model-performance-and-visualizing-results" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="evaluating-model-performance-and-visualizing-results"><span class="header-section-number">1.5</span> Evaluating Model Performance and Visualizing Results</h2>
<p>After training the models, we evaluate their performance using metrics like accuracy, AUC, and uplift curves. We also create plots to visualize the predictions and the treatment effects.</p>
<p>This helps us understand how well the models distinguish between customers who will respond to the treatment and those who won’t, and identify the most effective targeting strategies.</p>
<p>Plot 1: Cumulative Uplift (Logit Model)</p>
<p>The uplift model outperforms the propensity model by reaching 8% incremental uplift at 85% targeting. It shoots up quickly meaning we’re finding customers who really need our ads to buy, and after 85% it starts falling because now we’re targeting customers who buy less with ads. The propensity model climbs more slowly meaning it’s finding customers who are more likely to buy, but many would have bought anyway. The gap in the plots indicates the uplift model is creating more value for every dollar spent.</p>
<p>Plot 2: Incremental Uplift by Bin (Logit Model)</p>
<p>This chart sorts customers into bins to show how much value each group creates. The top 25% of customers are responsive to our ads in our uplift model. The propensity model bars are smaller and overall flatter because it can’t tell the difference between best and avg customers (it’s just going based on the probability of buying). The uplift performs worse at the end because the last 15% of customers are less likely to buy if we advertise to them.</p>
<div id="cell-11" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>uplift_complete(tab, tab_propen, df_master)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Breakeven threshold: 0.1001
Formula: Target customers where pred_treatment &gt; 0.1001
Optimal percentage: 20%
Maximum profit: $1,404.90
Customers above threshold: 8,647
Percentage to target: 48.0%
Optimal percentage: 25%
Maximum profit: $45,907.76
Customers above threshold: 1,974
Percentage to target: 21.9%

Propensity model
Profit: $1,404.90

Uplift model
Profit: $45,907.76</code></pre>
</div>
</div>
</section>
<section id="nonlinear-models-mlp" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="nonlinear-models-mlp"><span class="header-section-number">1.6</span> Nonlinear models (MLP)</h2>
<p>We started with linear regression to serve as our baseline and provide insights into feature importance, relationships and correlation with response. Next we will train nonlinear models starting with simple MLP. Nonlinear models help us capture non-linear relationships we may have missed. The chosen features are refined based on our results from linear regression. Moreover, we will tune our models using cross validation to optimize <strong>ROC AUC</strong></p>
<div id="cell-13" class="cell" data-execution_count="70">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>tab, tab_propen, df_master <span class="op">=</span> analyze_uplift(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    mlp_control, mlp_treatment, mlp_propensity, ci<span class="op">=</span><span class="va">False</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/..-..-_notebook-uplift_summ-cell-7-output-1.png" width="640" height="480" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/..-..-_notebook-uplift_summ-cell-7-output-2.png" width="640" height="480" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Expected incremental profit (uplift): 53521.38688147295
Expected incremental profit (propensity): -18225.063175122745</code></pre>
</div>
</div>
<p>Plot 1: Cumulative Uplift (MLP Model)</p>
<p>The uplift model significantly outperforms the propensity model, reaching about 9% incremental uplift compared to propensity’s 7.3%. The blue line climbs steeply at first, showing the MLP model is excellent at identifying customers who genuinely need ads to convert. The propensity model starts very flat—barely above random targeting (dotted line) for the first 30%—meaning it’s wasting budget on customers who’d buy anyway. After 90% targeting, the uplift line drops sharply as we hit customers who are actively turned off by advertising. The much larger gap between blue and the diagonal shows the uplift approach creates far more value per marketing dollar spent.</p>
<p>Plot 2: Incremental Uplift by Bin (MLP Model) Sorting customers into groups reveals dramatic differences. The uplift model shows massive performance in the first bin—nearly 30% uplift for the top 5% of customers. These are people who desperately need our ads to buy. The next few groups maintain strong 20-25% uplift. The propensity model has an unusual spike around bin 7 (around 35% targeting) showing it finds a pocket of likely buyers, but overall performs much more inconsistently. Most critically, the uplift model reveals the last two bins with -25% to -45% uplift—these customers find our ads so annoying they’re less likely to buy. The propensity model stays slightly negative at the end but misses the severity of this problem, leading to massive profit loss of -$18,225 while uplift generates $53,521 profit.</p>
<div id="cell-15" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>uplift_analysis(tab, tab_propen, df_master)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Breakeven threshold: 0.1001
Formula: Target customers where pred_treatment &gt; 0.1001
Optimal percentage: 50%
Maximum profit: $9,976.15
Customers above threshold: 7,607
Percentage to target: 42.3%
Optimal percentage: 30%
Maximum profit: $54,270.05
Customers above threshold: 2,459
Percentage to target: 27.3%

Propensity model
Profit: $9,976.15

Uplift model
Profit: $54,270.05</code></pre>
</div>
</div>
</section>
<section id="nonlinear-models-xgboost" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="nonlinear-models-xgboost"><span class="header-section-number">1.7</span> Nonlinear models (xgboost)</h2>
<p>Next we will model our solution using boosted trees (xgboost)</p>
<div id="cell-17" class="cell" data-execution_count="80">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>tab, tab_propen, df_master <span class="op">=</span> analyze_uplift(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    xgb_control, xgb_treatment, xgb_prospen, ci<span class="op">=</span><span class="va">False</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/..-..-_notebook-uplift_summ-cell-9-output-1.png" width="640" height="480" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/..-..-_notebook-uplift_summ-cell-9-output-2.png" width="640" height="480" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Expected incremental profit (uplift): 51110.03866766843
Expected incremental profit (propensity): -11220.531505886487</code></pre>
</div>
</div>
<p>Plot 1: Cumulative Uplift (XGBoost Model)</p>
<p>The uplift model dramatically outperforms the propensity model, reaching about 8.3% incremental uplift at 90% targeting compared to propensity’s 7.3%. The blue line rockets upward from the start, showing XGBoost excels at identifying customers who genuinely need ads to convert. The propensity model (red) starts extremely slowly—actually running below the random targeting line (dotted) for the first 15%—meaning it’s actively performing worse than random selection by wasting budget on customers who’d buy anyway. After 90% targeting, the uplift curve drops as we hit customers who respond negatively to advertising. The dramatically larger area between the blue line and the diagonal shows the uplift approach creates far more incremental value per dollar spent.</p>
<p>Plot 2: Incremental Uplift by Bin (XGBoost Model) This chart shows XGBoost’s strong customer segmentation. The uplift model delivers exceptional performance in the first bin—over 27% uplift for the top 5% of customers who desperately need ads. The next three bins maintain robust 17-23% uplift. The propensity model shows weak and inconsistent performance across all bins, with its best performance oddly appearing in the middle bins (30-35%) at around 17-18%, suggesting it’s confused about who the best customers actually are. Most critically, the uplift model reveals the last two bins with -28% to -43% uplift—customers so turned off by ads they’re far less likely to buy. The propensity model stays slightly positive throughout, completely missing these problematic customers, which explains why it loses $11,221 in profit while uplift generates $51,110.</p>
<div id="cell-19" class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>uplift_analysis(tab, tab_propen, df_master)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Breakeven threshold: 0.1001
Formula: Target customers where pred_treatment &gt; 0.1001
Optimal percentage: 55%
Maximum profit: $8,681.67
Customers above threshold: 7,863
Percentage to target: 43.7%
Optimal percentage: 35%
Maximum profit: $51,948.40
Customers above threshold: 2,565
Percentage to target: 28.5%

Propensity model
Profit: $8,681.67

Uplift model
Profit: $51,948.40</code></pre>
</div>
</div>
</section>
<section id="key-results" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="key-results"><span class="header-section-number">1.8</span> Key Results</h2>
<section id="baseline-uplift-model" class="level3" data-number="1.8.1">
<h3 data-number="1.8.1" class="anchored" data-anchor-id="baseline-uplift-model"><span class="header-section-number">1.8.1</span> Baseline Uplift Model</h3>
<ul>
<li>Uplift model reaches about <strong>8% incremental uplift at 85% targeting</strong>.</li>
<li>Propensity model grows slower and is less able to distinguish high-value, treatment-sensitive customers.</li>
<li>The uplift model creates more value early and avoids wasting effort on customers who would have converted anyway.</li>
</ul>
</section>
<section id="mlp-uplift-model" class="level3" data-number="1.8.2">
<h3 data-number="1.8.2" class="anchored" data-anchor-id="mlp-uplift-model"><span class="header-section-number">1.8.2</span> MLP Uplift Model</h3>
<ul>
<li>Uplift outperforms propensity:
<ul>
<li>~<strong>9% uplift</strong> vs <strong>7.3%</strong> for propensity.</li>
</ul></li>
<li>Top customers show very strong uplift:
<ul>
<li>nearly <strong>30% uplift for the top 5%</strong>.</li>
</ul></li>
<li>Last bins are strongly negative:
<ul>
<li>around <strong>-25% to -45% uplift</strong>, indicating customers harmed by advertising.</li>
</ul></li>
<li>Profit comparison:
<ul>
<li>uplift model generates <strong>+$53,521</strong></li>
<li>propensity model loses <strong>-$18,225</strong></li>
</ul></li>
</ul>
</section>
<section id="xgboost-uplift-model" class="level3" data-number="1.8.3">
<h3 data-number="1.8.3" class="anchored" data-anchor-id="xgboost-uplift-model"><span class="header-section-number">1.8.3</span> XGBoost Uplift Model</h3>
<ul>
<li>Uplift also outperforms propensity:
<ul>
<li>~<strong>8.3% uplift</strong> vs <strong>7.3%</strong> for propensity.</li>
</ul></li>
<li>Top 5% customers show:
<ul>
<li><strong>&gt;27% uplift</strong></li>
</ul></li>
<li>Last bins again show negative response:
<ul>
<li>around <strong>-28% to -43% uplift</strong></li>
</ul></li>
<li>Profit comparison:
<ul>
<li>uplift model generates <strong>+$51,110</strong></li>
<li>propensity model loses <strong>-$11,221</strong></li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="conclusion" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">1.9</span> Conclusion</h2>
<ul>
<li>The notebook shows that <strong>uplift modeling is more effective than propensity modeling</strong> for targeting treatment (ads).</li>
<li>Uplift models better identify:
<ul>
<li>customers who truly need the treatment,</li>
<li>customers who would convert anyway,</li>
<li>customers who are negatively impacted by treatment.</li>
</ul></li>
<li>The nonlinear models (MLP and XGBoost) demonstrate especially strong segmentation power, producing higher incremental lift and much better profit outcomes.</li>
<li>Overall, the analysis supports using uplift modeling to optimize marketing spend and avoid targeting customers who would either convert without treatment or respond negatively to it.</li>
</ul>
</section>
<a class="quarto-notebook-link" id="nblink-1" href="../../_notebook/uplift_summ-preview.html#cell-0">Source: Uplift Modeling Analysis</a></section>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>